### ISSUE TITLE
Field Guide: update Design Picker page

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/ganon-issues#57]
# Description

We need to add/update documentation to reflect the latest DP that is in production.
PCYsg-D3C-p2

 I expect the v13n DP to evolve,  **let's keep the documentation light.**  A screenshot of the MVP UI and a statement "we expect the way generated designs are presented in onboarding flow to evolve over Q3 2022."

# Acceptance Criteria
The following should be in the DP FG.

- [ ] Include info about how v13n/generated designs are created in RT and link to RT FG
- [ ] explanation of relationship between verticals screen, whitelisted(supported) verticals and how that impacts who sees generated designs
- [ ] a section that briefly explains recent history (maybe just sceenshots of prior DPs), this helps give context to show how we are continually evolving/improving the DP.
  - [ ]    link to [Ship Table](pbAok1-2MG-p2) with comment to check ship table for ship dates and history
- [ ] Clean up any outdate information on PCYsg-D3C-p2 

# Related
https://github.com/orgs/Automattic/projects/338/views/1

**Comment by autumnfjeld** [comment]
Note: @miksansegundo  Started working on this as part of https://github.com/Automattic/ganon-issues/issues/1.

The main goal for updating the DP page is to add a screen shot of UDP and also leave prior screenshots with dates they were in production - the point if for someone to be able to come to the DP page and understand its evolution and details about the current DP.

**Comment by miksansegundo** [comment]
I have done all the tasks and updated the page. Maybe someone else can add more details when reviewing my changes.

**Comment by autumnfjeld** [comment]
Thank you @miksansegundo !  I'll go ahead and close this as I've also added a bit of detail to the DP FG page. :)
